// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHKwRmiU9HaS1lS6_WdM3c2F8glqMFiFU',
    appId: '1:593302968970:web:ae2d73d0f99eebe3d66b73',
    messagingSenderId: '593302968970',
    projectId: 'fir-a0b73',
    authDomain: 'fir-a0b73.firebaseapp.com',
    storageBucket: 'fir-a0b73.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfyhV9F_lPTnk4v0SRc2r2iB88rnWveI4',
    appId: '1:593302968970:android:5832bc599b69023dd66b73',
    messagingSenderId: '593302968970',
    projectId: 'fir-a0b73',
    storageBucket: 'fir-a0b73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Oky95thn2kDvxe58JI_h2oAyCdP0LI0',
    appId: '1:593302968970:ios:1edbe07c2b308fa1d66b73',
    messagingSenderId: '593302968970',
    projectId: 'fir-a0b73',
    storageBucket: 'fir-a0b73.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-Oky95thn2kDvxe58JI_h2oAyCdP0LI0',
    appId: '1:593302968970:ios:1edbe07c2b308fa1d66b73',
    messagingSenderId: '593302968970',
    projectId: 'fir-a0b73',
    storageBucket: 'fir-a0b73.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
